palette = "tokyonight"

format = """
$directory\
$git_branch\
$git_status\
$java\
$nodejs\
$python\
$kubernetes\
$aws\
$opentofu\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[java]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[kubernetes]
disabled = false
symbol = "󱃾 "

[aws]
symbol = " "

[opentofu]
symbol = "󱁢 "

[cmd_duration]
min_time = 2_000

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[palettes.tokyonight]
rosewater = "#f7768e"
flamingo = "#f7768e"
pink = "#bb9af7"
mauve = "#bb9af7"
red = "#f7768e"
maroon = "#f7768e"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#1abc9c"
sky = "#7dcfff"
sapphire = "#7dcfff"
blue = "#7aa2f7"
lavender = "#7aa2f7"
text = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#a9b1d6"
overlay2 = "#737aa2"
overlay1 = "#565f89"
overlay0 = "#545c7e"
surface2 = "#3b4261"
surface1 = "#292e42"
surface0 = "#232433"
base = "#1a1b26"
mantle = "#16161e"
crust = "#13131e"
